frontend/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'frontend'

urlpatterns = [
    path('', Index.as_view(), name="Index"),
    path('signup/', SignUp.as_view(), name="SignUp"),
    path('signup-parent/', ParentSignUp.as_view(), name="ParentSignUp"),
    path('signup-teacher/', TeacherSignUp.as_view(), name="TeacherSignUp"),
    path('teacher-onboarding/', TeacherOnboarding.as_view(), name="TeacherOnboarding"),
]

owncloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    # custom apps
    path("", include("frontend.urls")),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

class Index(TemplateView):
    template_name = 'home.html'

class SignUp(TemplateView):
    template_name = 'signup.html'

class ParentSignUp(TemplateView):
    template_name = 'parent.html'

class TeacherSignUp(TemplateView):
    template_name = 'teacher.html'

class TeacherOnboarding(TemplateView):
    template_name = 'teacheronboarding.html'

frontend/templates/parent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Signup - Parent</title>
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-content-center p-5">
            <div class="col-lg-6 px-5 pt-1 pb-4 border border-2 rounded-5">
                <form action="" method="POST">
                    {% csrf_token %}
                    <i class="fal fa-user-circle fa-7x my-3 text-center w-100"></i>
                    <h5 class="p-1 text-center">Sign In</h5>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/apple.svg' %}" class="object-fill w-25" height="30" width="40">
                            <p class="w-75 mb-0">Sign in with Apple</p>
                        </div>
                    </a>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/google.svg' %}" class="object-fill w-25" height="30" width="50">
                            <p class="w-75 mb-0">Sign in with Google</p>
                        </div>
                    </a>
                    <p class="text-between-line mt-4"><span>OR</span></p>
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="username"  placeholder="Enter full name" required>
                    </div>
                    <div class="mb-3">
                      <label class="form-label">Email address</label>
                      <input type="email" class="form-control" id="email" name="email"  placeholder="Email" required>
                      <div class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <p class="text-between-line mt-4"><span>Your kid's information</span></p>
                    <div class="mb-3">
                        <label class="form-label">Birthdate</label>
                        <input type="date" class="form-control" id="birthdate" name="birthdate"  placeholder="Enter birthdate" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username"  placeholder="Enter unique username" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Grade</label>
                        <input type="text" class="form-control" id="grade" name="grade" required>
                    </div>
                    <button class="btn btn-outline-dark my-2" type="button" onclick="addKid()">Add Kid</button>
                    <table class="table table-bordered" id="kids-table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Birthdate</th>
                            <th scope="col">Grade</th>
                          </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-save text-light px-5 fw-bold fs-5 py-2 my-2">Sign Up</button>
                    <div class="form-text py-2">By clicking Sign Up you're agreeing to, Primer's 
                        <span class="text-main fw-bold">Terms Of Service</span>, including our 
                        <span class="text-main fw-bold">Code Of Conduct</span>, and our 
                        <span class="text-main fw-bold">Privacy Policy</span> 
                    </div>
                    <a href="" class="text-dark">Already have a account? <span class="text-main fw-bold">Sign In</span></a>
                  </form>
            </div>
        </div>
    </div>

    <script>
        var kids_count = 0;
        function addKid(){
            var username = $("#username").val();
            var birthdate = $("#birthdate").val();
            var grade = $("#grade").val();


            if (username && birthdate && grade){
                if (kids_count < 4){
                    var find_row = $(`#${username}`).length;
                    if (find_row <= 0){
                        kids_count ++;
                        var tr = `
                        <tr id="${username}">
                            <th scope="row">${kids_count}</th>
                            <td>${username}</td>
                            <td>${birthdate}</td>
                            <td>${grade}</td>
                        </tr>`;
                        $('#kids-table tbody').append(tr);
                    }
                    else{
                        new AWN().alert('Kid has already been added with that username!');
                    }
                }
                else{
                    new AWN().warning('You can only add upto 4 kids!');
                }
            }
            else{
                new AWN().alert('Required fields for kids missing!');
            }
        }
    </script>
{% endblock content %}s

frontend/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Signup</title>
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center" style="height:550px">
            <div class="d-flex flex-column justify-content-center align-items-center align-self-start mt-4 border border-2 border-dark rounded-5" style="width:500px">
                <img class="object-fill mt-3" src="{% static 'images/logo.png' %}" width="100" height="100" style="border-radius:50px">
                <h5 class="font-monospace p-3">I am a ..</h5>
                <div class="d-flex flex-row justify-content-center align-items-center my-2">
                    <a href="{% url 'frontend:TeacherSignUp' %}" class="btn btn-outline-dark fs-4 mx-2 px-5">Teacher</a>
                    <a href="{% url 'frontend:ParentSignUp' %}" class="btn btn-outline-dark fs-4 mx-2 px-5">Parent</a>
                </div>
                <a class="text-center cursor-pointer text-dark mt-2 mb-4" href="{% url 'frontend:SignUp' %}">Already have a account! Sign-up in</a>
            </div>
        </div>
    </div>
{% endblock content %}s

frontend/templates/teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Signup - Teacher</title>
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-content-center p-5">
            <div class="col-lg-6 px-5 pt-1 pb-4 border border-2 rounded-5">
                <form action="row" method="POST">
                    {% csrf_token %}
                    <i class="fal fa-user-circle fa-7x my-3 text-center w-100"></i>
                    <h5 class="p-1 text-center">Sign In</h5>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/apple.svg' %}" class="object-fill w-25" height="30" width="40">
                            <p class="w-75 mb-0">Sign in with Apple</p>
                        </div>
                    </a>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/google.svg' %}" class="object-fill w-25" height="30" width="50">
                            <p class="w-75 mb-0">Sign in with Google</p>
                        </div>
                    </a>
                    <p class="text-between-line mt-4"><span>OR</span></p>
                    <div class="d-flex flex-row justify-content-between">
                        <div class="col-md-3 pr-2 mb-3">
                            <label class="form-label">Title</label>
                            <select class="form-select" name="title">
                                <option class="text-muted" selected>Title</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                        <div class="col-md-9 mb-3">
                          <label class="form-label">First Name</label>
                          <input type="email" class="form-control" id="first-name" name="first-name" placeholder="Enter first name" required>
                        </div>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label class="form-label">Last Name</label>
                        <input type="email" class="form-control" id="last-name" name="last-name" placeholder="Enter last name" required>
                      </div>
                      <div class="d-flex flex-row justify-content-between">
                        <div class="col-md-6 pr-2 mb-3">
                            <label class="form-label">Educator Role</label>
                            <select class="form-select" name="educator-role">
                                <option class="text-muted" selected>Educator Role</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Grade</label>
                            <select class="form-select" name="grade">
                                <option class="text-muted" selected>Grade</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label class="form-label">Reading Level System</label>
                        <select class="form-select" name="reading-level-system">
                            <option class="text-muted" selected>Reading Level System</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label class="form-label">School Name or Address</label>
                        <input type="email" class="form-control" id="school" name="school" placeholder="Enter school name or address" required>
                      </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-save text-light px-5 fw-bold fs-5 py-2 my-2">Sign Up</button>
                    <div class="form-text py-2">By clicking Sign Up you're agreeing to, Primer's 
                        <span class="text-main fw-bold">Terms Of Service</span>, including our 
                        <span class="text-main fw-bold">Code Of Conduct</span>, and our 
                        <span class="text-main fw-bold">Privacy Policy</span> 
                    </div>
                    <a href="" class="text-dark">Already have a account? <span class="text-main fw-bold">Sign In</span></a>
                  </form>
            </div>
        </div>
    </div>
{% endblock content %}s

frontend/templates/teacheronboarding.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Signup - Parent</title>
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-content-center p-5">
            <div class="col-lg-6 px-5 pt-1 pb-4 border border-2 rounded-5">
                <form action="" method="POST">
                    {% csrf_token %}
                    <i class="fal fa-user-circle fa-7x my-3 text-center w-100"></i>
                    <h5 class="p-1 text-center">Sign In</h5>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/apple.svg' %}" class="object-fill w-25" height="30" width="40">
                            <p class="w-75 mb-0">Sign in with Apple</p>
                        </div>
                    </a>
                    <a href="" class="d-flex justify-content-center text-dark">
                        <div class="d-flex flex-row p-2 align-items-center my-2 border rounded w-50  zoom">
                            <img src="{% static 'images/google.svg' %}" class="object-fill w-25" height="30" width="50">
                            <p class="w-75 mb-0">Sign in with Google</p>
                        </div>
                    </a>
                    <p class="text-between-line mt-4"><span>OR</span></p>
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="username"  placeholder="Enter full name" required>
                    </div>
                    <div class="mb-3">
                      <label class="form-label">Email address</label>
                      <input type="email" class="form-control" id="email" name="email"  placeholder="Email" required>
                      <div class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <p class="text-between-line mt-4"><span>Your kid's information</span></p>
                    <div class="mb-3">
                        <label class="form-label">Birthdate</label>
                        <input type="date" class="form-control" id="birthdate" name="birthdate"  placeholder="Enter birthdate" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username"  placeholder="Enter unique username" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Grade</label>
                        <input type="text" class="form-control" id="grade" name="grade" required>
                    </div>
                    <button class="btn btn-outline-dark my-2" type="button" onclick="addKid()">Add Kid</button>
                    <table class="table table-bordered" id="kids-table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Birthdate</th>
                            <th scope="col">Grade</th>
                          </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-save text-light px-5 fw-bold fs-5 py-2 my-2">Sign Up</button>
                    <div class="form-text py-2">By clicking Sign Up you're agreeing to, Primer's 
                        <span class="text-main fw-bold">Terms Of Service</span>, including our 
                        <span class="text-main fw-bold">Code Of Conduct</span>, and our 
                        <span class="text-main fw-bold">Privacy Policy</span> 
                    </div>
                    <a href="" class="text-dark">Already have a account? <span class="text-main fw-bold">Sign In</span></a>
                  </form>
            </div>
        </div>
    </div>

    <script>
        var kids_count = 0;
        function addKid(){
            var username = $("#username").val();
            var birthdate = $("#birthdate").val();
            var grade = $("#grade").val();


            if (username && birthdate && grade){
                if (kids_count < 4){
                    var find_row = $(`#${username}`).length;
                    if (find_row <= 0){
                        kids_count ++;
                        var tr = `
                        <tr id="${username}">
                            <th scope="row">${kids_count}</th>
                            <td>${username}</td>
                            <td>${birthdate}</td>
                            <td>${grade}</td>
                        </tr>`;
                        $('#kids-table tbody').append(tr);
                    }
                    else{
                        new AWN().alert('Kid has already been added with that username!');
                    }
                }
                else{
                    new AWN().warning('You can only add upto 4 kids!');
                }
            }
            else{
                new AWN().alert('Required fields for kids missing!');
            }
        }
    </script>
{% endblock content %}s

templates/auth_head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_signup.css' %}">
    <title>OwnCloud</title>



</head>

<body>

{% block content %}{% endblock %}


<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>
{% block script %}{% endblock %}

</body>

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Notifications -->
    <link rel="stylesheet" href=" {% static 'css/notifications.css' %} ">
    <script src=" {% static 'js/notifications.var.js' %} " type="text/javascript"></script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- FontAwesome 5 -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    {% block title %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'frontend:Index' %}">
          <img class="object-fill ml-2" src="{% static 'images/logo.png' %}" alt="" width="60" height="50" class="d-inline-block align-text-top">
        </a>
        <a class="btn btn-outline-primary px-5" href="{% url 'frontend:SignUp' %}">Sign up today</a>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    
    <!-- <footer>
      <div class="position-absolute bottom-0 w-100 text-center p-2 bg-white">All rights reserved © 2022</div>
    </footer> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <div class="row p-5">
            <div class="col-lg-6">
                <h5 class="pt-5">A safe video-sharing platform for kids.<br><br>
                    G3MS is a place where kids use web3 tools to improve their academics and learn life skills
                    like money management and relationships. Now parents can enjoy screen time guilt-free
                    with weekly reports!<br><br>     
                    Best for ages 4-12. Sign up to join our private Beta TODAY!
                </h5>
            </div>
            <div class="col-lg-6 d-flex justify-content-center align-items-center flex-column">
                <h5 class="btn btn-outline-secondary text-dark px-5">Where learning is social</h5>
                <iframe width="100%" height="315"
                src="https://www.youtube.com/embed/tgbNymZ7vqY">
                </iframe>
            </div>
            <a class="btn btn-outline-primary px-5 col-lg-2 ml-2" href="{% url 'frontend:SignUp' %}">Sign up today</a>
        </div>
    </div>
{% endblock content %}s